# AUTO-GENERATED by generate_types — do not edit manually
from __future__ import annotations
from pydantic import BaseModel
from typing import Any, Optional, Union


class Main:
    class inputs(BaseModel):
        n: int = 10
        population_size: int = 5
        generations: int = 10

    class outputs(BaseModel):
        generation: int
        pi: float

    class parameters(BaseModel):
        pass


class Montecarlo:
    class inputs(BaseModel):
        n: int = 1000

    class outputs(BaseModel):
        inside: int
        total: int
        ratio: float
        pi_estimate: float

    class parameters(BaseModel):
        pass

