apiVersion: v1
kind: ConfigMap
metadata:
  name: test-workflow-{{DEPLOYMENT_ID}}
  namespace: swarmopt
  
apiVersion: batch/v1
kind: Job
metadata:
  name: test-workflow-{{DEPLOYMENT_ID}}
  namespace: swarmopt
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hello
          image: python:3.12-slim
          command:
            - sh
            - -c
            - pip install redis --quiet && python /scripts/main.py
